spring:
  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  driver-class-name: com.mysql.cj.jdbc.Driver
  password: rootroot
  url: jdbc:mysql://localhost:3306/coffeemukka_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  username: root

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true

#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        default_batch_fetch_size: 100

  profiles:
    active: local
    include: secret

  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB

  messages:
    basename: i18n/exception,i18n/validation